/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebSeriesRouteImport } from './routes/web-series'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as TopRatedRouteImport } from './routes/top-rated'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShortFilmsRouteImport } from './routes/short-films'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MatureRouteImport } from './routes/mature'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocumentariesRouteImport } from './routes/documentaries'
import { Route as AnimeRouteImport } from './routes/anime'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'
import { Route as MatureTrendingRouteImport } from './routes/mature.trending'
import { Route as MaturePsychologicalRouteImport } from './routes/mature.psychological'
import { Route as MatureNoirRouteImport } from './routes/mature.noir'
import { Route as MatureAnimeRouteImport } from './routes/mature.anime'
import { Route as KidsMoviesRouteImport } from './routes/kids.movies'
import { Route as KidsCartoonsRouteImport } from './routes/kids.cartoons'
import { Route as KidsAnimeRouteImport } from './routes/kids.anime'
import { Route as AnimeTrendingRouteImport } from './routes/anime.trending'
import { Route as AnimeTopRatedRouteImport } from './routes/anime.top-rated'
import { Route as AnimeGenresRouteImport } from './routes/anime.genres'
import { Route as AnimeAnimeIdRouteImport } from './routes/anime.$animeId'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDnaRouteImport } from './routes/_authenticated/dna'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedHeatmapMovieIdRouteImport } from './routes/_authenticated/heatmap.$movieId'
import { Route as AuthenticatedAdminThemesRouteImport } from './routes/_authenticated/admin/themes'
import { Route as AuthenticatedAdminSchedulerRouteImport } from './routes/_authenticated/admin/scheduler'
import { Route as AuthenticatedAdminReviewsRouteImport } from './routes/_authenticated/admin/reviews'
import { Route as AuthenticatedAdminMoviesRouteImport } from './routes/_authenticated/admin/movies'
import { Route as AuthenticatedAdminMoodsRouteImport } from './routes/_authenticated/admin/moods'
import { Route as AuthenticatedAdminHeatmapRouteImport } from './routes/_authenticated/admin/heatmap'
import { Route as AuthenticatedAdminComplaintsRouteImport } from './routes/_authenticated/admin/complaints'
import { Route as AuthenticatedAdminBroadcastRouteImport } from './routes/_authenticated/admin/broadcast'

const WebSeriesRoute = WebSeriesRouteImport.update({
  id: '/web-series',
  path: '/web-series',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRatedRoute = TopRatedRouteImport.update({
  id: '/top-rated',
  path: '/top-rated',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortFilmsRoute = ShortFilmsRouteImport.update({
  id: '/short-films',
  path: '/short-films',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MatureRoute = MatureRouteImport.update({
  id: '/mature',
  path: '/mature',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentariesRoute = DocumentariesRouteImport.update({
  id: '/documentaries',
  path: '/documentaries',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRoute = AnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatureTrendingRoute = MatureTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => MatureRoute,
} as any)
const MaturePsychologicalRoute = MaturePsychologicalRouteImport.update({
  id: '/psychological',
  path: '/psychological',
  getParentRoute: () => MatureRoute,
} as any)
const MatureNoirRoute = MatureNoirRouteImport.update({
  id: '/noir',
  path: '/noir',
  getParentRoute: () => MatureRoute,
} as any)
const MatureAnimeRoute = MatureAnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => MatureRoute,
} as any)
const KidsMoviesRoute = KidsMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => KidsRoute,
} as any)
const KidsCartoonsRoute = KidsCartoonsRouteImport.update({
  id: '/cartoons',
  path: '/cartoons',
  getParentRoute: () => KidsRoute,
} as any)
const KidsAnimeRoute = KidsAnimeRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => KidsRoute,
} as any)
const AnimeTrendingRoute = AnimeTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => AnimeRoute,
} as any)
const AnimeTopRatedRoute = AnimeTopRatedRouteImport.update({
  id: '/top-rated',
  path: '/top-rated',
  getParentRoute: () => AnimeRoute,
} as any)
const AnimeGenresRoute = AnimeGenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => AnimeRoute,
} as any)
const AnimeAnimeIdRoute = AnimeAnimeIdRouteImport.update({
  id: '/$animeId',
  path: '/$animeId',
  getParentRoute: () => AnimeRoute,
} as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDnaRoute = AuthenticatedDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedHeatmapMovieIdRoute =
  AuthenticatedHeatmapMovieIdRouteImport.update({
    id: '/heatmap/$movieId',
    path: '/heatmap/$movieId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminThemesRoute =
  AuthenticatedAdminThemesRouteImport.update({
    id: '/themes',
    path: '/themes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSchedulerRoute =
  AuthenticatedAdminSchedulerRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewsRoute =
  AuthenticatedAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoviesRoute =
  AuthenticatedAdminMoviesRouteImport.update({
    id: '/movies',
    path: '/movies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMoodsRoute = AuthenticatedAdminMoodsRouteImport.update({
  id: '/moods',
  path: '/moods',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHeatmapRoute =
  AuthenticatedAdminHeatmapRouteImport.update({
    id: '/heatmap',
    path: '/heatmap',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminComplaintsRoute =
  AuthenticatedAdminComplaintsRouteImport.update({
    id: '/complaints',
    path: '/complaints',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBroadcastRoute =
  AuthenticatedAdminBroadcastRouteImport.update({
    id: '/broadcast',
    path: '/broadcast',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteWithChildren
  '/documentaries': typeof DocumentariesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kids': typeof KidsRouteWithChildren
  '/login': typeof LoginRoute
  '/mature': typeof MatureRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/short-films': typeof ShortFilmsRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/web-series': typeof WebSeriesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/anime/genres': typeof AnimeGenresRoute
  '/anime/top-rated': typeof AnimeTopRatedRoute
  '/anime/trending': typeof AnimeTrendingRoute
  '/kids/anime': typeof KidsAnimeRoute
  '/kids/cartoons': typeof KidsCartoonsRoute
  '/kids/movies': typeof KidsMoviesRoute
  '/mature/anime': typeof MatureAnimeRoute
  '/mature/noir': typeof MatureNoirRoute
  '/mature/psychological': typeof MaturePsychologicalRoute
  '/mature/trending': typeof MatureTrendingRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/heatmap': typeof AuthenticatedAdminHeatmapRoute
  '/admin/moods': typeof AuthenticatedAdminMoodsRoute
  '/admin/movies': typeof AuthenticatedAdminMoviesRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/scheduler': typeof AuthenticatedAdminSchedulerRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/heatmap/$movieId': typeof AuthenticatedHeatmapMovieIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anime': typeof AnimeRouteWithChildren
  '/documentaries': typeof DocumentariesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kids': typeof KidsRouteWithChildren
  '/login': typeof LoginRoute
  '/mature': typeof MatureRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/short-films': typeof ShortFilmsRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/web-series': typeof WebSeriesRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/anime/genres': typeof AnimeGenresRoute
  '/anime/top-rated': typeof AnimeTopRatedRoute
  '/anime/trending': typeof AnimeTrendingRoute
  '/kids/anime': typeof KidsAnimeRoute
  '/kids/cartoons': typeof KidsCartoonsRoute
  '/kids/movies': typeof KidsMoviesRoute
  '/mature/anime': typeof MatureAnimeRoute
  '/mature/noir': typeof MatureNoirRoute
  '/mature/psychological': typeof MaturePsychologicalRoute
  '/mature/trending': typeof MatureTrendingRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/admin/heatmap': typeof AuthenticatedAdminHeatmapRoute
  '/admin/moods': typeof AuthenticatedAdminMoodsRoute
  '/admin/movies': typeof AuthenticatedAdminMoviesRoute
  '/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/admin/scheduler': typeof AuthenticatedAdminSchedulerRoute
  '/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/heatmap/$movieId': typeof AuthenticatedHeatmapMovieIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/anime': typeof AnimeRouteWithChildren
  '/documentaries': typeof DocumentariesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kids': typeof KidsRouteWithChildren
  '/login': typeof LoginRoute
  '/mature': typeof MatureRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/short-films': typeof ShortFilmsRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/top-rated': typeof TopRatedRoute
  '/trending': typeof TrendingRoute
  '/web-series': typeof WebSeriesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/dna': typeof AuthenticatedDnaRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/anime/$animeId': typeof AnimeAnimeIdRoute
  '/anime/genres': typeof AnimeGenresRoute
  '/anime/top-rated': typeof AnimeTopRatedRoute
  '/anime/trending': typeof AnimeTrendingRoute
  '/kids/anime': typeof KidsAnimeRoute
  '/kids/cartoons': typeof KidsCartoonsRoute
  '/kids/movies': typeof KidsMoviesRoute
  '/mature/anime': typeof MatureAnimeRoute
  '/mature/noir': typeof MatureNoirRoute
  '/mature/psychological': typeof MaturePsychologicalRoute
  '/mature/trending': typeof MatureTrendingRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
  '/_authenticated/admin/broadcast': typeof AuthenticatedAdminBroadcastRoute
  '/_authenticated/admin/complaints': typeof AuthenticatedAdminComplaintsRoute
  '/_authenticated/admin/heatmap': typeof AuthenticatedAdminHeatmapRoute
  '/_authenticated/admin/moods': typeof AuthenticatedAdminMoodsRoute
  '/_authenticated/admin/movies': typeof AuthenticatedAdminMoviesRoute
  '/_authenticated/admin/reviews': typeof AuthenticatedAdminReviewsRoute
  '/_authenticated/admin/scheduler': typeof AuthenticatedAdminSchedulerRoute
  '/_authenticated/admin/themes': typeof AuthenticatedAdminThemesRoute
  '/_authenticated/heatmap/$movieId': typeof AuthenticatedHeatmapMovieIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anime'
    | '/documentaries'
    | '/forgot-password'
    | '/kids'
    | '/login'
    | '/mature'
    | '/reset-password'
    | '/search'
    | '/short-films'
    | '/signup'
    | '/subscription'
    | '/top-rated'
    | '/trending'
    | '/web-series'
    | '/admin'
    | '/complaints'
    | '/dna'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/watchlist'
    | '/anime/$animeId'
    | '/anime/genres'
    | '/anime/top-rated'
    | '/anime/trending'
    | '/kids/anime'
    | '/kids/cartoons'
    | '/kids/movies'
    | '/mature/anime'
    | '/mature/noir'
    | '/mature/psychological'
    | '/mature/trending'
    | '/movies/$movieId'
    | '/admin/broadcast'
    | '/admin/complaints'
    | '/admin/heatmap'
    | '/admin/moods'
    | '/admin/movies'
    | '/admin/reviews'
    | '/admin/scheduler'
    | '/admin/themes'
    | '/heatmap/$movieId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anime'
    | '/documentaries'
    | '/forgot-password'
    | '/kids'
    | '/login'
    | '/mature'
    | '/reset-password'
    | '/search'
    | '/short-films'
    | '/signup'
    | '/subscription'
    | '/top-rated'
    | '/trending'
    | '/web-series'
    | '/complaints'
    | '/dna'
    | '/history'
    | '/notifications'
    | '/profile'
    | '/watchlist'
    | '/anime/$animeId'
    | '/anime/genres'
    | '/anime/top-rated'
    | '/anime/trending'
    | '/kids/anime'
    | '/kids/cartoons'
    | '/kids/movies'
    | '/mature/anime'
    | '/mature/noir'
    | '/mature/psychological'
    | '/mature/trending'
    | '/movies/$movieId'
    | '/admin/broadcast'
    | '/admin/complaints'
    | '/admin/heatmap'
    | '/admin/moods'
    | '/admin/movies'
    | '/admin/reviews'
    | '/admin/scheduler'
    | '/admin/themes'
    | '/heatmap/$movieId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/anime'
    | '/documentaries'
    | '/forgot-password'
    | '/kids'
    | '/login'
    | '/mature'
    | '/reset-password'
    | '/search'
    | '/short-films'
    | '/signup'
    | '/subscription'
    | '/top-rated'
    | '/trending'
    | '/web-series'
    | '/_authenticated/admin'
    | '/_authenticated/complaints'
    | '/_authenticated/dna'
    | '/_authenticated/history'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/watchlist'
    | '/anime/$animeId'
    | '/anime/genres'
    | '/anime/top-rated'
    | '/anime/trending'
    | '/kids/anime'
    | '/kids/cartoons'
    | '/kids/movies'
    | '/mature/anime'
    | '/mature/noir'
    | '/mature/psychological'
    | '/mature/trending'
    | '/movies/$movieId'
    | '/_authenticated/admin/broadcast'
    | '/_authenticated/admin/complaints'
    | '/_authenticated/admin/heatmap'
    | '/_authenticated/admin/moods'
    | '/_authenticated/admin/movies'
    | '/_authenticated/admin/reviews'
    | '/_authenticated/admin/scheduler'
    | '/_authenticated/admin/themes'
    | '/_authenticated/heatmap/$movieId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AnimeRoute: typeof AnimeRouteWithChildren
  DocumentariesRoute: typeof DocumentariesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KidsRoute: typeof KidsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MatureRoute: typeof MatureRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ShortFilmsRoute: typeof ShortFilmsRoute
  SignupRoute: typeof SignupRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TopRatedRoute: typeof TopRatedRoute
  TrendingRoute: typeof TrendingRoute
  WebSeriesRoute: typeof WebSeriesRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web-series': {
      id: '/web-series'
      path: '/web-series'
      fullPath: '/web-series'
      preLoaderRoute: typeof WebSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-rated': {
      id: '/top-rated'
      path: '/top-rated'
      fullPath: '/top-rated'
      preLoaderRoute: typeof TopRatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/short-films': {
      id: '/short-films'
      path: '/short-films'
      fullPath: '/short-films'
      preLoaderRoute: typeof ShortFilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mature': {
      id: '/mature'
      path: '/mature'
      fullPath: '/mature'
      preLoaderRoute: typeof MatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentaries': {
      id: '/documentaries'
      path: '/documentaries'
      fullPath: '/documentaries'
      preLoaderRoute: typeof DocumentariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mature/trending': {
      id: '/mature/trending'
      path: '/trending'
      fullPath: '/mature/trending'
      preLoaderRoute: typeof MatureTrendingRouteImport
      parentRoute: typeof MatureRoute
    }
    '/mature/psychological': {
      id: '/mature/psychological'
      path: '/psychological'
      fullPath: '/mature/psychological'
      preLoaderRoute: typeof MaturePsychologicalRouteImport
      parentRoute: typeof MatureRoute
    }
    '/mature/noir': {
      id: '/mature/noir'
      path: '/noir'
      fullPath: '/mature/noir'
      preLoaderRoute: typeof MatureNoirRouteImport
      parentRoute: typeof MatureRoute
    }
    '/mature/anime': {
      id: '/mature/anime'
      path: '/anime'
      fullPath: '/mature/anime'
      preLoaderRoute: typeof MatureAnimeRouteImport
      parentRoute: typeof MatureRoute
    }
    '/kids/movies': {
      id: '/kids/movies'
      path: '/movies'
      fullPath: '/kids/movies'
      preLoaderRoute: typeof KidsMoviesRouteImport
      parentRoute: typeof KidsRoute
    }
    '/kids/cartoons': {
      id: '/kids/cartoons'
      path: '/cartoons'
      fullPath: '/kids/cartoons'
      preLoaderRoute: typeof KidsCartoonsRouteImport
      parentRoute: typeof KidsRoute
    }
    '/kids/anime': {
      id: '/kids/anime'
      path: '/anime'
      fullPath: '/kids/anime'
      preLoaderRoute: typeof KidsAnimeRouteImport
      parentRoute: typeof KidsRoute
    }
    '/anime/trending': {
      id: '/anime/trending'
      path: '/trending'
      fullPath: '/anime/trending'
      preLoaderRoute: typeof AnimeTrendingRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/anime/top-rated': {
      id: '/anime/top-rated'
      path: '/top-rated'
      fullPath: '/anime/top-rated'
      preLoaderRoute: typeof AnimeTopRatedRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/anime/genres': {
      id: '/anime/genres'
      path: '/genres'
      fullPath: '/anime/genres'
      preLoaderRoute: typeof AnimeGenresRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/anime/$animeId': {
      id: '/anime/$animeId'
      path: '/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AnimeAnimeIdRouteImport
      parentRoute: typeof AnimeRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dna': {
      id: '/_authenticated/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof AuthenticatedDnaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/heatmap/$movieId': {
      id: '/_authenticated/heatmap/$movieId'
      path: '/heatmap/$movieId'
      fullPath: '/heatmap/$movieId'
      preLoaderRoute: typeof AuthenticatedHeatmapMovieIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/themes': {
      id: '/_authenticated/admin/themes'
      path: '/themes'
      fullPath: '/admin/themes'
      preLoaderRoute: typeof AuthenticatedAdminThemesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/scheduler': {
      id: '/_authenticated/admin/scheduler'
      path: '/scheduler'
      fullPath: '/admin/scheduler'
      preLoaderRoute: typeof AuthenticatedAdminSchedulerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reviews': {
      id: '/_authenticated/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AuthenticatedAdminReviewsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/movies': {
      id: '/_authenticated/admin/movies'
      path: '/movies'
      fullPath: '/admin/movies'
      preLoaderRoute: typeof AuthenticatedAdminMoviesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moods': {
      id: '/_authenticated/admin/moods'
      path: '/moods'
      fullPath: '/admin/moods'
      preLoaderRoute: typeof AuthenticatedAdminMoodsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/heatmap': {
      id: '/_authenticated/admin/heatmap'
      path: '/heatmap'
      fullPath: '/admin/heatmap'
      preLoaderRoute: typeof AuthenticatedAdminHeatmapRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/complaints': {
      id: '/_authenticated/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AuthenticatedAdminComplaintsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/broadcast': {
      id: '/_authenticated/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBroadcastRoute: typeof AuthenticatedAdminBroadcastRoute
  AuthenticatedAdminComplaintsRoute: typeof AuthenticatedAdminComplaintsRoute
  AuthenticatedAdminHeatmapRoute: typeof AuthenticatedAdminHeatmapRoute
  AuthenticatedAdminMoodsRoute: typeof AuthenticatedAdminMoodsRoute
  AuthenticatedAdminMoviesRoute: typeof AuthenticatedAdminMoviesRoute
  AuthenticatedAdminReviewsRoute: typeof AuthenticatedAdminReviewsRoute
  AuthenticatedAdminSchedulerRoute: typeof AuthenticatedAdminSchedulerRoute
  AuthenticatedAdminThemesRoute: typeof AuthenticatedAdminThemesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBroadcastRoute: AuthenticatedAdminBroadcastRoute,
  AuthenticatedAdminComplaintsRoute: AuthenticatedAdminComplaintsRoute,
  AuthenticatedAdminHeatmapRoute: AuthenticatedAdminHeatmapRoute,
  AuthenticatedAdminMoodsRoute: AuthenticatedAdminMoodsRoute,
  AuthenticatedAdminMoviesRoute: AuthenticatedAdminMoviesRoute,
  AuthenticatedAdminReviewsRoute: AuthenticatedAdminReviewsRoute,
  AuthenticatedAdminSchedulerRoute: AuthenticatedAdminSchedulerRoute,
  AuthenticatedAdminThemesRoute: AuthenticatedAdminThemesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedDnaRoute: typeof AuthenticatedDnaRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedHeatmapMovieIdRoute: typeof AuthenticatedHeatmapMovieIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedDnaRoute: AuthenticatedDnaRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedHeatmapMovieIdRoute: AuthenticatedHeatmapMovieIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AnimeRouteChildren {
  AnimeAnimeIdRoute: typeof AnimeAnimeIdRoute
  AnimeGenresRoute: typeof AnimeGenresRoute
  AnimeTopRatedRoute: typeof AnimeTopRatedRoute
  AnimeTrendingRoute: typeof AnimeTrendingRoute
}

const AnimeRouteChildren: AnimeRouteChildren = {
  AnimeAnimeIdRoute: AnimeAnimeIdRoute,
  AnimeGenresRoute: AnimeGenresRoute,
  AnimeTopRatedRoute: AnimeTopRatedRoute,
  AnimeTrendingRoute: AnimeTrendingRoute,
}

const AnimeRouteWithChildren = AnimeRoute._addFileChildren(AnimeRouteChildren)

interface KidsRouteChildren {
  KidsAnimeRoute: typeof KidsAnimeRoute
  KidsCartoonsRoute: typeof KidsCartoonsRoute
  KidsMoviesRoute: typeof KidsMoviesRoute
}

const KidsRouteChildren: KidsRouteChildren = {
  KidsAnimeRoute: KidsAnimeRoute,
  KidsCartoonsRoute: KidsCartoonsRoute,
  KidsMoviesRoute: KidsMoviesRoute,
}

const KidsRouteWithChildren = KidsRoute._addFileChildren(KidsRouteChildren)

interface MatureRouteChildren {
  MatureAnimeRoute: typeof MatureAnimeRoute
  MatureNoirRoute: typeof MatureNoirRoute
  MaturePsychologicalRoute: typeof MaturePsychologicalRoute
  MatureTrendingRoute: typeof MatureTrendingRoute
}

const MatureRouteChildren: MatureRouteChildren = {
  MatureAnimeRoute: MatureAnimeRoute,
  MatureNoirRoute: MatureNoirRoute,
  MaturePsychologicalRoute: MaturePsychologicalRoute,
  MatureTrendingRoute: MatureTrendingRoute,
}

const MatureRouteWithChildren =
  MatureRoute._addFileChildren(MatureRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AnimeRoute: AnimeRouteWithChildren,
  DocumentariesRoute: DocumentariesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KidsRoute: KidsRouteWithChildren,
  LoginRoute: LoginRoute,
  MatureRoute: MatureRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ShortFilmsRoute: ShortFilmsRoute,
  SignupRoute: SignupRoute,
  SubscriptionRoute: SubscriptionRoute,
  TopRatedRoute: TopRatedRoute,
  TrendingRoute: TrendingRoute,
  WebSeriesRoute: WebSeriesRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
